"""'archiwizacja'

Revision ID: 57213bdc65ee
Revises: 472b251da852
Create Date: 2020-11-29 11:55:09.457788

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '57213bdc65ee'
down_revision = '472b251da852'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('board', sa.Column('archived', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('board', 'archived')
    # ### end Alembic commands ###
