"""empty message

Revision ID: 7ac7547c67b5
Revises: 9b51b937fa70
Create Date: 2020-12-15 17:57:32.405503

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7ac7547c67b5'
down_revision = '9b51b937fa70'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('card', sa.Column('index', sa.Integer(), nullable=True))
    op.add_column('list', sa.Column('index', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('list', 'index')
    op.drop_column('card', 'index')
    # ### end Alembic commands ###
