"""public_boards

Revision ID: 80efdfb39d78
Revises: 32988536753a
Create Date: 2020-12-03 14:21:24.608027

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '80efdfb39d78'
down_revision = '32988536753a'
branch_labels = None
depends_on = None



def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('board', sa.Column('public', sa.Boolean(),default=False, nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('board', 'public')
    # ### end Alembic commands ###
