"""empty message

Revision ID: f8b9fca7fde4
Revises: 7ac7547c67b5
Create Date: 2021-01-04 18:07:35.419350

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f8b9fca7fde4'
down_revision = '7ac7547c67b5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activity',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('board_id', sa.Integer(), nullable=False),
    sa.Column('who', sa.String(length=50), nullable=True),
    sa.Column('what', sa.String(length=150), nullable=True),
    sa.Column('date_done', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['board_id'], ['board.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('activity')
    # ### end Alembic commands ###
